use public SparkR java methods
SparkTC/r4ml pull request #40
Opened 2017-06-01 06:05 UTC by hungple

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

2017-06-01 06:20 UTC, bdwyer2 requested changes

2017-06-01 06:20 UTC, bdwyer2 commented on R4ML/R/java.bridge.R
> +        level_jref <- sparkR.callJStatic("org.apache.log4j.Level", "toLevel", level)
We have decided to use `SparkR::` for all our SparkR functions. Can you please change this to `SparkR::sparkR.callJStatic`?

2017-06-01 15:52 UTC, hungple commented on R4ML/R/java.bridge.R
> +        level_jref <- sparkR.callJStatic("org.apache.log4j.Level", "toLevel", level)
only for callJStatic?  How about callJMethod?

2017-06-01 17:52 UTC, bdwyer2 commented on R4ML/R/java.bridge.R
> +        level_jref <- sparkR.callJStatic("org.apache.log4j.Level", "toLevel", level)
For both. Every public function from SparkR should start with `SparkR::` and every private function should start with `SparkR:::`.

2017-06-01 19:17 UTC, hungple commented
@bdwyer2 I have added "::" for any place that we call "callJMethod" and "callJStatic".  Please review and approve. Thanks.

2017-06-01 19:24 UTC, bdwyer2 approved these changes

2017-06-19 21:47 UTC, CarmenRuppach commented
@aloknsingh can this PR get merged?

2017-06-20 01:53 UTC, closed without merging